// Global using directives

global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.Net;
global using System.Net.NetworkInformation;
global using System.Net.Sockets;
global using System.Threading;
global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.Behaviors;
global using CommunityToolkit.Maui.Core;
global using CommunityToolkit.Maui.Core.Platform;
global using CommunityToolkit.Maui.Markup;
global using CommunityToolkit.Maui.Views;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Markdig;
global using Microsoft.Data.Sqlite;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.FluentUI.AspNetCore.Components;
global using Microsoft.JSInterop;
global using Microsoft.Maui.Controls.Shapes;
global using Microsoft.Maui.Layouts;
global using Microsoft.Maui.Storage;
global using Ormur.Components.Layout;
global using Ormur.Data;
global using Ormur.Data.Models;
global using Ormur.i18n;
global using Ormur.Services;
global using Icons = Microsoft.FluentUI.AspNetCore.Components.Icons;
global using Path = System.IO.Path;