//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ormur.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ormur.i18n.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Unterordner hinfügen.
        /// </summary>
        internal static string HomeAddNewSubfolder {
            get {
                return ResourceManager.GetString("HomeAddNewSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        internal static string HomeCreate {
            get {
                return ResourceManager.GetString("HomeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string HomeDelete {
            get {
                return ResourceManager.GetString("HomeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie den Ordner &quot;{0}&quot; wirklich löschen?.
        /// </summary>
        internal static string HomeDeleteConfirmText {
            get {
                return ResourceManager.GetString("HomeDeleteConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dies wird auch alle Unterordner und Notizen in diesem Ordner löschen..
        /// </summary>
        internal static string HomeDeleteConfirmTextTwo {
            get {
                return ResourceManager.GetString("HomeDeleteConfirmTextTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner löschen.
        /// </summary>
        internal static string HomeDeleteFolder {
            get {
                return ResourceManager.GetString("HomeDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner löschen.
        /// </summary>
        internal static string HomeDelteFolder {
            get {
                return ResourceManager.GetString("HomeDelteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string HomeDismiss {
            get {
                return ResourceManager.GetString("HomeDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner filtern:.
        /// </summary>
        internal static string HomeFilterFolder {
            get {
                return ResourceManager.GetString("HomeFilterFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Ordner.
        /// </summary>
        internal static string HomeNewFolderHeader {
            get {
                return ResourceManager.GetString("HomeNewFolderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Unterordner.
        /// </summary>
        internal static string HomeNewSubfolder {
            get {
                return ResourceManager.GetString("HomeNewSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Ordners....
        /// </summary>
        internal static string HomePlaceholder {
            get {
                return ResourceManager.GetString("HomePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner suchen....
        /// </summary>
        internal static string HomeSearchFolder {
            get {
                return ResourceManager.GetString("HomeSearchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Ordner.
        /// </summary>
        internal static string HomeSideNavAllFolders {
            get {
                return ResourceManager.GetString("HomeSideNavAllFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        internal static string HomeSideNavFavourites {
            get {
                return ResourceManager.GetString("HomeSideNavFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notizen.
        /// </summary>
        internal static string HomeSideNavNotice {
            get {
                return ResourceManager.GetString("HomeSideNavNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Unterordners....
        /// </summary>
        internal static string HomeSubfolderPlaceholder {
            get {
                return ResourceManager.GetString("HomeSubfolderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was möchtest du für {0} machen?.
        /// </summary>
        internal static string HomeSubfolderWhatTodo {
            get {
                return ResourceManager.GetString("HomeSubfolderWhatTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groß.
        /// </summary>
        internal static string MdBold {
            get {
                return ResourceManager.GetString("MdBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string MdEditorHeader {
            get {
                return ResourceManager.GetString("MdEditorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern....
        /// </summary>
        internal static string MdIsSaving {
            get {
                return ResourceManager.GetString("MdIsSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursivschrift.
        /// </summary>
        internal static string MdItalic {
            get {
                return ResourceManager.GetString("MdItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste mit Zahlen.
        /// </summary>
        internal static string MdNbList {
            get {
                return ResourceManager.GetString("MdNbList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Zeile.
        /// </summary>
        internal static string MdNewLine {
            get {
                return ResourceManager.GetString("MdNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notiz Titel....
        /// </summary>
        internal static string MdPlaceholderOne {
            get {
                return ResourceManager.GetString("MdPlaceholderOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschau.
        /// </summary>
        internal static string MdPreviewHeader {
            get {
                return ResourceManager.GetString("MdPreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string MdStore {
            get {
                return ResourceManager.GetString("MdStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string MdTodosHeader {
            get {
                return ResourceManager.GetString("MdTodosHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        internal static string MdUlList {
            get {
                return ResourceManager.GetString("MdUlList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startseite.
        /// </summary>
        internal static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string NavSettings {
            get {
                return ResourceManager.GetString("NavSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisierung.
        /// </summary>
        internal static string NavSync {
            get {
                return ResourceManager.GetString("NavSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache:.
        /// </summary>
        internal static string SettingsCultureHeader {
            get {
                return ResourceManager.GetString("SettingsCultureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dunkel blau.
        /// </summary>
        internal static string SettingsDarkBlueColor {
            get {
                return ResourceManager.GetString("SettingsDarkBlueColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grün.
        /// </summary>
        internal static string SettingsGreenColor {
            get {
                return ResourceManager.GetString("SettingsGreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lila.
        /// </summary>
        internal static string SettingsPurpleColor {
            get {
                return ResourceManager.GetString("SettingsPurpleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell.
        /// </summary>
        internal static string SettingsStandardColor {
            get {
                return ResourceManager.GetString("SettingsStandardColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbthema.
        /// </summary>
        internal static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie die IP des anderen Geräts ein....
        /// </summary>
        internal static string SyncErrorOne {
            get {
                return ResourceManager.GetString("SyncErrorOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisation fehlgeschlagen: {0}..
        /// </summary>
        internal static string SyncErrorTwo {
            get {
                return ResourceManager.GetString("SyncErrorTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerätesynchronisation.
        /// </summary>
        internal static string SyncHeader {
            get {
                return ResourceManager.GetString("SyncHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Geräte-IP:.
        /// </summary>
        internal static string SyncIpAddress {
            get {
                return ResourceManager.GetString("SyncIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP wird ermittelt....
        /// </summary>
        internal static string SyncIpLoad {
            get {
                return ResourceManager.GetString("SyncIpLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Adresse nicht verfügbar. Prüfen Sie Ihre Netzwerk....
        /// </summary>
        internal static string SyncIpNotHere {
            get {
                return ResourceManager.GetString("SyncIpNotHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie auf &quot;Synchronisation starten&quot;..
        /// </summary>
        internal static string SyncLiFour {
            get {
                return ResourceManager.GetString("SyncLiFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stellen Sie sicher, dass beide Geräte im gleichen WLAN-Netzwerk sind (Hotspot aktivieren)..
        /// </summary>
        internal static string SyncLiOne {
            get {
                return ResourceManager.GetString("SyncLiOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie die IP-Adresse des anderen Geräts ein..
        /// </summary>
        internal static string SyncLiThree {
            get {
                return ResourceManager.GetString("SyncLiThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starten Sie die Synchronisation auf einem Gerät..
        /// </summary>
        internal static string SyncLiTwo {
            get {
                return ResourceManager.GetString("SyncLiTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisation starten.
        /// </summary>
        internal static string SyncStartSync {
            get {
                return ResourceManager.GetString("SyncStartSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So synchronisieren Sie:.
        /// </summary>
        internal static string SyncSubHeader {
            get {
                return ResourceManager.GetString("SyncSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisation erfolgreich!.
        /// </summary>
        internal static string SyncSuccess {
            get {
                return ResourceManager.GetString("SyncSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wird synchronisiert....
        /// </summary>
        internal static string SyncSyncLoad {
            get {
                return ResourceManager.GetString("SyncSyncLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung zum Gerät wird hergestellt....
        /// </summary>
        internal static string SyncWillBe {
            get {
                return ResourceManager.GetString("SyncWillBe", resourceCulture);
            }
        }
    }
}
