//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ormur.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ormur.i18n.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Unterordner hinfügen.
        /// </summary>
        internal static string HomeAddNewSubfolder {
            get {
                return ResourceManager.GetString("HomeAddNewSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        internal static string HomeCreate {
            get {
                return ResourceManager.GetString("HomeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string HomeDelete {
            get {
                return ResourceManager.GetString("HomeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner löschen.
        /// </summary>
        internal static string HomeDeleteFolder {
            get {
                return ResourceManager.GetString("HomeDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner löschen.
        /// </summary>
        internal static string HomeDelteFolder {
            get {
                return ResourceManager.GetString("HomeDelteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string HomeDismiss {
            get {
                return ResourceManager.GetString("HomeDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner filtern:.
        /// </summary>
        internal static string HomeFilterFolder {
            get {
                return ResourceManager.GetString("HomeFilterFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Ordner.
        /// </summary>
        internal static string HomeNewFolderHeader {
            get {
                return ResourceManager.GetString("HomeNewFolderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Unterordner.
        /// </summary>
        internal static string HomeNewSubfolder {
            get {
                return ResourceManager.GetString("HomeNewSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Ordners....
        /// </summary>
        internal static string HomePlaceholder {
            get {
                return ResourceManager.GetString("HomePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Ordner.
        /// </summary>
        internal static string HomeSideNavAllFolders {
            get {
                return ResourceManager.GetString("HomeSideNavAllFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        internal static string HomeSideNavFavourites {
            get {
                return ResourceManager.GetString("HomeSideNavFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notizen.
        /// </summary>
        internal static string HomeSideNavNotice {
            get {
                return ResourceManager.GetString("HomeSideNavNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was möchtest du für {0} machen?.
        /// </summary>
        internal static string HomeSubfolderWhatTodo {
            get {
                return ResourceManager.GetString("HomeSubfolderWhatTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startseite.
        /// </summary>
        internal static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string NavSettings {
            get {
                return ResourceManager.GetString("NavSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisierung.
        /// </summary>
        internal static string NavSync {
            get {
                return ResourceManager.GetString("NavSync", resourceCulture);
            }
        }
    }
}
