//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ormur.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ormur.i18n.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als .txt exportieren.
        /// </summary>
        internal static string ExportAsTxt {
            get {
                return ResourceManager.GetString("ExportAsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Exportieren.
        /// </summary>
        internal static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wird exportiert....
        /// </summary>
        internal static string ExportInProgress {
            get {
                return ResourceManager.GetString("ExportInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur Text.
        /// </summary>
        internal static string ExportOptionPlainText {
            get {
                return ResourceManager.GetString("ExportOptionPlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export als lesbarer Text ohne Formatierung.
        /// </summary>
        internal static string ExportOptionPlainTextDesc {
            get {
                return ResourceManager.GetString("ExportOptionPlainTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown erhalten.
        /// </summary>
        internal static string ExportOptionPreserveMarkdown {
            get {
                return ResourceManager.GetString("ExportOptionPreserveMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export mit originaler Markdown-Formatierung.
        /// </summary>
        internal static string ExportOptionPreserveMarkdownDesc {
            get {
                return ResourceManager.GetString("ExportOptionPreserveMarkdownDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie möchtest du deine Notiz exportieren?.
        /// </summary>
        internal static string ExportOptionsDescription {
            get {
                return ResourceManager.GetString("ExportOptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Optionen.
        /// </summary>
        internal static string ExportOptionsTitle {
            get {
                return ResourceManager.GetString("ExportOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text erfolgreich als {0} exportiert.
        /// </summary>
        internal static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ormur verwendet keine Cloud. Alle Ihre Daten werden lokal auf Ihrem Computer oder Handy in einer SQLite-Datenbank gespeichert..
        /// </summary>
        internal static string FaqDataPrivacyContent1 {
            get {
                return ResourceManager.GetString("FaqDataPrivacyContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das bedeutet, dass Ihre Daten Ihnen gehören und niemand außer Ihnen Zugriff darauf hat. Ihre Daten werden nicht gesammelt und bleiben privat und sicher auf Ihrem Gerät..
        /// </summary>
        internal static string FaqDataPrivacyContent2 {
            get {
                return ResourceManager.GetString("FaqDataPrivacyContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind meine Daten privat und sicher?.
        /// </summary>
        internal static string FaqDataPrivacyTitle {
            get {
                return ResourceManager.GetString("FaqDataPrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier finden Sie Antworten auf die am häufigsten gestellten Fragen..
        /// </summary>
        internal static string FaqDescription {
            get {
                return ResourceManager.GetString("FaqDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Syntax ist sehr einfach zu verwenden und ermöglicht ein professionelleres Erscheinungsbild sowie größere Flexibilität..
        /// </summary>
        internal static string FaqMarkdownContent1 {
            get {
                return ResourceManager.GetString("FaqMarkdownContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist beispielsweise möglich, HTML zu verwenden, um Text einzufärben oder die Größe eines Bildes zu ändern..
        /// </summary>
        internal static string FaqMarkdownContent2 {
            get {
                return ResourceManager.GetString("FaqMarkdownContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie müssen HTML nicht kennen. Die Markdown-Syntax ist sehr intuitiv und Sie sind nicht verpflichtet, sie zu verwenden..
        /// </summary>
        internal static string FaqMarkdownContent3 {
            get {
                return ResourceManager.GetString("FaqMarkdownContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie können auch nur reinen Text verwenden, wenn Sie möchten..
        /// </summary>
        internal static string FaqMarkdownContent4 {
            get {
                return ResourceManager.GetString("FaqMarkdownContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warum die Markdown-Syntax verwenden?.
        /// </summary>
        internal static string FaqMarkdownTitle {
            get {
                return ResourceManager.GetString("FaqMarkdownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja. Da sie eine SQLite-Datenbank verwendet, die Daten direkt auf Ihrem Gerät speichert, benötigen Sie kein Internet..
        /// </summary>
        internal static string FaqOfflineContent {
            get {
                return ResourceManager.GetString("FaqOfflineContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktioniert die App offline?.
        /// </summary>
        internal static string FaqOfflineTitle {
            get {
                return ResourceManager.GetString("FaqOfflineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So viele Sie möchten. SQLite kann mehrere Terabyte an Daten speichern, auch wenn es unwahrscheinlich ist, dass Sie diese Grenze erreichen..
        /// </summary>
        internal static string FaqSqliteLimitContent {
            get {
                return ResourceManager.GetString("FaqSqliteLimitContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie viele Notizen können in einer SQLite-Datenbank gespeichert werden?.
        /// </summary>
        internal static string FaqSqliteLimitTitle {
            get {
                return ResourceManager.GetString("FaqSqliteLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ormur ist Open-Source. Das bedeutet, dass der Quellcode für alle verfügbar ist..
        /// </summary>
        internal static string FaqSupportContent1 {
            get {
                return ResourceManager.GetString("FaqSupportContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn Sie auf ein Problem stoßen, zögern Sie nicht, einen Kommentar zu hinterlassen oder, wenn Sie ein GitHub-Konto haben, dort eine Nachricht zu schreiben:.
        /// </summary>
        internal static string FaqSupportContent2 {
            get {
                return ResourceManager.GetString("FaqSupportContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ormur auf GitHub..
        /// </summary>
        internal static string FaqSupportGithubLink {
            get {
                return ResourceManager.GetString("FaqSupportGithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich habe ein Problem, das ich nicht lösen kann, wie kann ich Hilfe bekommen?.
        /// </summary>
        internal static string FaqSupportTitle {
            get {
                return ResourceManager.GetString("FaqSupportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja, das ist möglich. Folgen Sie einfach den Anweisungen auf der Seite..
        /// </summary>
        internal static string FaqSyncContent1 {
            get {
                return ResourceManager.GetString("FaqSyncContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beachten Sie jedoch, dass wenn Sie Ihre Daten von einem Gerät auf ein anderes synchronisieren möchten,.
        /// </summary>
        internal static string FaqSyncContent2 {
            get {
                return ResourceManager.GetString("FaqSyncContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zum Beispiel von Ihrem Handy auf Ihre Desktop-Anwendung, dies alle Daten auf der Desktop-Anwendung löschen wird.
        /// </summary>
        internal static string FaqSyncContent3 {
            get {
                return ResourceManager.GetString("FaqSyncContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to und sie durch die Daten von Ihrem Handy ersetzt werden..
        /// </summary>
        internal static string FaqSyncContent4 {
            get {
                return ResourceManager.GetString("FaqSyncContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Synchronisieren Ihrer Daten ist eine gute Sache, wenn Sie auf beiden Geräten immer die gleichen Daten haben möchten..
        /// </summary>
        internal static string FaqSyncContent5 {
            get {
                return ResourceManager.GetString("FaqSyncContent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dies ist jedoch nur möglich, wenn Sie den Hotspot Ihres Handys verwenden..
        /// </summary>
        internal static string FaqSyncContent6 {
            get {
                return ResourceManager.GetString("FaqSyncContent6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich habe die Android-App, kann ich meine Daten synchronisieren?.
        /// </summary>
        internal static string FaqSyncTitle {
            get {
                return ResourceManager.GetString("FaqSyncTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Häufig gestellte Fragen.
        /// </summary>
        internal static string FaqTitle {
            get {
                return ResourceManager.GetString("FaqTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ormur bedeutet.
        /// </summary>
        internal static string FaqWhyNameContent1 {
            get {
                return ResourceManager.GetString("FaqWhyNameContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auf Isländisch..
        /// </summary>
        internal static string FaqWhyNameContent2 {
            get {
                return ResourceManager.GetString("FaqWhyNameContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es bezieht sich auf die Midgardschlange (Sohn des trickreichen Gottes Loki) in der nordischen Mythologie, die die Erde umschloss..
        /// </summary>
        internal static string FaqWhyNameContent3 {
            get {
                return ResourceManager.GetString("FaqWhyNameContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ormur ist ein mythologisches Wesen, das uns Stabilität verleiht und uns daran erinnert, dass alles vergänglich ist, sogar unser Gedächtnis..
        /// </summary>
        internal static string FaqWhyNameContent4 {
            get {
                return ResourceManager.GetString("FaqWhyNameContent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deshalb müssen wir Notizen machen, um nichts zu vergessen..
        /// </summary>
        internal static string FaqWhyNameContent5 {
            get {
                return ResourceManager.GetString("FaqWhyNameContent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlange.
        /// </summary>
        internal static string FaqWhyNameSerpent {
            get {
                return ResourceManager.GetString("FaqWhyNameSerpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warum der Name Ormur?.
        /// </summary>
        internal static string FaqWhyNameTitle {
            get {
                return ResourceManager.GetString("FaqWhyNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Ordnername muss mindestens 1 Zeichen lang sein.
        /// </summary>
        internal static string FolderNameTooShort {
            get {
                return ResourceManager.GetString("FolderNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Speichern des Ordners. Bitte versuchen Sie es erneut..
        /// </summary>
        internal static string FolderSaveError {
            get {
                return ResourceManager.GetString("FolderSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Unterordner hinfügen.
        /// </summary>
        internal static string HomeAddNewSubfolder {
            get {
                return ResourceManager.GetString("HomeAddNewSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        internal static string HomeCreate {
            get {
                return ResourceManager.GetString("HomeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string HomeDelete {
            get {
                return ResourceManager.GetString("HomeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie den Ordner &quot;{0}&quot; wirklich löschen?.
        /// </summary>
        internal static string HomeDeleteConfirmText {
            get {
                return ResourceManager.GetString("HomeDeleteConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dies wird auch alle Unterordner und Notizen in diesem Ordner löschen..
        /// </summary>
        internal static string HomeDeleteConfirmTextTwo {
            get {
                return ResourceManager.GetString("HomeDeleteConfirmTextTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner löschen.
        /// </summary>
        internal static string HomeDeleteFolder {
            get {
                return ResourceManager.GetString("HomeDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner löschen.
        /// </summary>
        internal static string HomeDelteFolder {
            get {
                return ResourceManager.GetString("HomeDelteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string HomeDismiss {
            get {
                return ResourceManager.GetString("HomeDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner filtern:.
        /// </summary>
        internal static string HomeFilterFolder {
            get {
                return ResourceManager.GetString("HomeFilterFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Ordner.
        /// </summary>
        internal static string HomeNewFolderHeader {
            get {
                return ResourceManager.GetString("HomeNewFolderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Unterordner.
        /// </summary>
        internal static string HomeNewSubfolder {
            get {
                return ResourceManager.GetString("HomeNewSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Ordners....
        /// </summary>
        internal static string HomePlaceholder {
            get {
                return ResourceManager.GetString("HomePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner suchen....
        /// </summary>
        internal static string HomeSearchFolder {
            get {
                return ResourceManager.GetString("HomeSearchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Ordner.
        /// </summary>
        internal static string HomeSideNavAllFolders {
            get {
                return ResourceManager.GetString("HomeSideNavAllFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoriten.
        /// </summary>
        internal static string HomeSideNavFavourites {
            get {
                return ResourceManager.GetString("HomeSideNavFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notizen.
        /// </summary>
        internal static string HomeSideNavNotice {
            get {
                return ResourceManager.GetString("HomeSideNavNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Unterordners....
        /// </summary>
        internal static string HomeSubfolderPlaceholder {
            get {
                return ResourceManager.GetString("HomeSubfolderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was möchtest du für {0} machen?.
        /// </summary>
        internal static string HomeSubfolderWhatTodo {
            get {
                return ResourceManager.GetString("HomeSubfolderWhatTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie einen gültigen Ordnernamen ein.
        /// </summary>
        internal static string InvalidFolderName {
            get {
                return ResourceManager.GetString("InvalidFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie einen gültigen Unterordnernamen ein.
        /// </summary>
        internal static string InvalidSubfolderName {
            get {
                return ResourceManager.GetString("InvalidSubfolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erweiterte Formatierung.
        /// </summary>
        internal static string MarkdownAdvancedFormatting {
            get {
                return ResourceManager.GetString("MarkdownAdvancedFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grundlegende Formatierung.
        /// </summary>
        internal static string MarkdownBasicFormatting {
            get {
                return ResourceManager.GetString("MarkdownBasicFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Fett**.
        /// </summary>
        internal static string MarkdownBoldExample {
            get {
                return ResourceManager.GetString("MarkdownBoldExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Spickzettel.
        /// </summary>
        internal static string MarkdownCheatSheetLink {
            get {
                return ResourceManager.GetString("MarkdownCheatSheetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kode.
        /// </summary>
        internal static string MarkdownCode {
            get {
                return ResourceManager.GetString("MarkdownCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        ```
        ///           Mehrzeiliger
        ///           Codeblock
        ///        ```
        ///    .
        /// </summary>
        internal static string MarkdownCodeBlockExample {
            get {
                return ResourceManager.GetString("MarkdownCodeBlockExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbiger Text.
        /// </summary>
        internal static string MarkdownColoredText {
            get {
                return ResourceManager.GetString("MarkdownColoredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Überschrift 1.
        /// </summary>
        internal static string MarkdownHeader1Example {
            get {
                return ResourceManager.GetString("MarkdownHeader1Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Überschrift 2.
        /// </summary>
        internal static string MarkdownHeader2Example {
            get {
                return ResourceManager.GetString("MarkdownHeader2Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschriften.
        /// </summary>
        internal static string MarkdownHeaders {
            get {
                return ResourceManager.GetString("MarkdownHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown Hilfe.
        /// </summary>
        internal static string MarkdownHelpTitle {
            get {
                return ResourceManager.GetString("MarkdownHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis: HTML kann verwendet werden, wird aber nicht empfohlen.
        /// </summary>
        internal static string MarkdownHtmlNote {
            get {
                return ResourceManager.GetString("MarkdownHtmlNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ![Alt-Text](bild.jpg).
        /// </summary>
        internal static string MarkdownImageExample {
            get {
                return ResourceManager.GetString("MarkdownImageExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie können Bilder mit HTML img-Tag und Inline-Styles formatieren.
        /// </summary>
        internal static string MarkdownImageNote {
            get {
                return ResourceManager.GetString("MarkdownImageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `Inline-Code`.
        /// </summary>
        internal static string MarkdownInlineCodeExample {
            get {
                return ResourceManager.GetString("MarkdownInlineCodeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Kursiv*.
        /// </summary>
        internal static string MarkdownItalicExample {
            get {
                return ResourceManager.GetString("MarkdownItalicExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfahren Sie mehr über Markdown-Syntax:.
        /// </summary>
        internal static string MarkdownLearnMoreText {
            get {
                return ResourceManager.GetString("MarkdownLearnMoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Linktext](https://example.com).
        /// </summary>
        internal static string MarkdownLinkExample {
            get {
                return ResourceManager.GetString("MarkdownLinkExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links und Bilder.
        /// </summary>
        internal static string MarkdownLinksImages {
            get {
                return ResourceManager.GetString("MarkdownLinksImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Ungeordnete Liste
        ///      - Unterpunkt
        ///    1. Geordnete Liste
        ///    2. Zweiter Punkt.
        /// </summary>
        internal static string MarkdownListExample {
            get {
                return ResourceManager.GetString("MarkdownListExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen.
        /// </summary>
        internal static string MarkdownLists {
            get {
                return ResourceManager.GetString("MarkdownLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Ressourcen.
        /// </summary>
        internal static string MarkdownMoreResources {
            get {
                return ResourceManager.GetString("MarkdownMoreResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~~Durchgestrichen~~.
        /// </summary>
        internal static string MarkdownStrikethroughExample {
            get {
                return ResourceManager.GetString("MarkdownStrikethroughExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestyltes Bild.
        /// </summary>
        internal static string MarkdownStyledImage {
            get {
                return ResourceManager.GetString("MarkdownStyledImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            | Spalte 1 | Spalte 2 |
        ///            |----------|----------|
        ///            | Zelle 1  | Zelle 2  |
        ///        .
        /// </summary>
        internal static string MarkdownTableExample {
            get {
                return ResourceManager.GetString("MarkdownTableExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabellen.
        /// </summary>
        internal static string MarkdownTables {
            get {
                return ResourceManager.GetString("MarkdownTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was ist Markdown?.
        /// </summary>
        internal static string MarkdownWhatIs {
            get {
                return ResourceManager.GetString("MarkdownWhatIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown ist eine einfache Auszeichnungssprache, mit der Sie formatierten Text erstellen können. Sie können Überschriften, Listen, Links und mehr formatieren, ohne komplexe HTML-Tags verwenden zu müssen..
        /// </summary>
        internal static string MarkdownWhatIsText {
            get {
                return ResourceManager.GetString("MarkdownWhatIsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string MdAdd {
            get {
                return ResourceManager.GetString("MdAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo hinzufügen.
        /// </summary>
        internal static string MdAddTodoMessage {
            get {
                return ResourceManager.GetString("MdAddTodoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groß.
        /// </summary>
        internal static string MdBold {
            get {
                return ResourceManager.GetString("MdBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten werden geladen....
        /// </summary>
        internal static string MdDataLoading {
            get {
                return ResourceManager.GetString("MdDataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string MdEditorHeader {
            get {
                return ResourceManager.GetString("MdEditorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild.
        /// </summary>
        internal static string MdImage {
            get {
                return ResourceManager.GetString("MdImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern....
        /// </summary>
        internal static string MdIsSaving {
            get {
                return ResourceManager.GetString("MdIsSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursivschrift.
        /// </summary>
        internal static string MdItalic {
            get {
                return ResourceManager.GetString("MdItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string MdLink {
            get {
                return ResourceManager.GetString("MdLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr über Markdowns Syntax.
        /// </summary>
        internal static string MdMoreAboutMd {
            get {
                return ResourceManager.GetString("MdMoreAboutMd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste mit Zahlen.
        /// </summary>
        internal static string MdNbList {
            get {
                return ResourceManager.GetString("MdNbList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Zeile.
        /// </summary>
        internal static string MdNewLine {
            get {
                return ResourceManager.GetString("MdNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Todo.
        /// </summary>
        internal static string MdNewTodo {
            get {
                return ResourceManager.GetString("MdNewTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schreibe etwas im Editor, um die Vorschau zu sehen.
        /// </summary>
        internal static string MdNothingWrote {
            get {
                return ResourceManager.GetString("MdNothingWrote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch keine Todos.
        /// </summary>
        internal static string MdNoTodo {
            get {
                return ResourceManager.GetString("MdNoTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notiz Titel....
        /// </summary>
        internal static string MdPlaceholderOne {
            get {
                return ResourceManager.GetString("MdPlaceholderOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschau.
        /// </summary>
        internal static string MdPreviewHeader {
            get {
                return ResourceManager.GetString("MdPreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zitat.
        /// </summary>
        internal static string MdQuote {
            get {
                return ResourceManager.GetString("MdQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string MdStore {
            get {
                return ResourceManager.GetString("MdStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wurde erfolgreich gespeichert.
        /// </summary>
        internal static string MdSuccess {
            get {
                return ResourceManager.GetString("MdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabellen.
        /// </summary>
        internal static string MdTables {
            get {
                return ResourceManager.GetString("MdTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabe.
        /// </summary>
        internal static string MdTask {
            get {
                return ResourceManager.GetString("MdTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was hast du im Kopf?.
        /// </summary>
        internal static string MdTextareaPlaceholder {
            get {
                return ResourceManager.GetString("MdTextareaPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestrichelt.
        /// </summary>
        internal static string MdThrough {
            get {
                return ResourceManager.GetString("MdThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string MdTitle {
            get {
                return ResourceManager.GetString("MdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo Beschreibung....
        /// </summary>
        internal static string MdTodoPlaceholder {
            get {
                return ResourceManager.GetString("MdTodoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string MdTodosHeader {
            get {
                return ResourceManager.GetString("MdTodosHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        internal static string MdUlList {
            get {
                return ResourceManager.GetString("MdUlList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterstricht.
        /// </summary>
        internal static string MdUnderline {
            get {
                return ResourceManager.GetString("MdUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entwickelt bei Cyprien de Fontenay.
        /// </summary>
        internal static string NavDeveloped {
            get {
                return ResourceManager.GetString("NavDeveloped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string NavFaq {
            get {
                return ResourceManager.GetString("NavFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startseite.
        /// </summary>
        internal static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string NavSettings {
            get {
                return ResourceManager.GetString("NavSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisierung.
        /// </summary>
        internal static string NavSync {
            get {
                return ResourceManager.GetString("NavSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Ordner anzeigen.
        /// </summary>
        internal static string NoFavoritesAction {
            get {
                return ResourceManager.GetString("NoFavoritesAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben noch keine Ordner als Favoriten markiert. Markieren Sie einen Ordner mit einem Stern, um ihn hier anzuzeigen..
        /// </summary>
        internal static string NoFavoritesMessage {
            get {
                return ResourceManager.GetString("NoFavoritesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch keine Favoriten.
        /// </summary>
        internal static string NoFavoritesTitle {
            get {
                return ResourceManager.GetString("NoFavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Text zum Exportieren vorhanden.
        /// </summary>
        internal static string NoTextToExport {
            get {
                return ResourceManager.GetString("NoTextToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache:.
        /// </summary>
        internal static string SettingsCultureHeader {
            get {
                return ResourceManager.GetString("SettingsCultureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dunkel blau.
        /// </summary>
        internal static string SettingsDarkBlueColor {
            get {
                return ResourceManager.GetString("SettingsDarkBlueColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grün.
        /// </summary>
        internal static string SettingsGreenColor {
            get {
                return ResourceManager.GetString("SettingsGreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lila.
        /// </summary>
        internal static string SettingsPurpleColor {
            get {
                return ResourceManager.GetString("SettingsPurpleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell.
        /// </summary>
        internal static string SettingsStandardColor {
            get {
                return ResourceManager.GetString("SettingsStandardColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farbthema.
        /// </summary>
        internal static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt am.
        /// </summary>
        internal static string SubCreatedOn {
            get {
                return ResourceManager.GetString("SubCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstelle eine neue Notiz, um loszulegen.
        /// </summary>
        internal static string SubCreateNotePrompt {
            get {
                return ResourceManager.GetString("SubCreateNotePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Notiz.
        /// </summary>
        internal static string SubDefaultNoteTitle {
            get {
                return ResourceManager.GetString("SubDefaultNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        internal static string SubEdit {
            get {
                return ResourceManager.GetString("SubEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Speichern des Unterordners. Bitte versuchen Sie es erneut..
        /// </summary>
        internal static string SubfolderSaveError {
            get {
                return ResourceManager.GetString("SubfolderSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Notiz.
        /// </summary>
        internal static string SubNewNote {
            get {
                return ResourceManager.GetString("SubNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch keine Notizen.
        /// </summary>
        internal static string SubNoNotes {
            get {
                return ResourceManager.GetString("SubNoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            Verbindung fehlgeschlagen. Bitte überprüfen Sie, dass beide Geräte im selben Netzwerk sind - Dass die IP-Adresse korrekt ist- Dass die App auf dem anderen Gerät geöffnet ist
        ///        .
        /// </summary>
        internal static string SyncConnectionFailed {
            get {
                return ResourceManager.GetString("SyncConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindungstest fehlgeschlagen: Timeout.
        /// </summary>
        internal static string SyncConnectionTimeout {
            get {
                return ResourceManager.GetString("SyncConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopieren der IP-Adresse fehlgeschlagen.
        /// </summary>
        internal static string SyncCopyFailed {
            get {
                return ResourceManager.GetString("SyncCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie die IP des anderen Geräts ein....
        /// </summary>
        internal static string SyncErrorOne {
            get {
                return ResourceManager.GetString("SyncErrorOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisation fehlgeschlagen: {0}..
        /// </summary>
        internal static string SyncErrorTwo {
            get {
                return ResourceManager.GetString("SyncErrorTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateifehler:.
        /// </summary>
        internal static string SyncFileError {
            get {
                return ResourceManager.GetString("SyncFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerätesynchronisation.
        /// </summary>
        internal static string SyncHeader {
            get {
                return ResourceManager.GetString("SyncHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Geräte-IP:.
        /// </summary>
        internal static string SyncIpAddress {
            get {
                return ResourceManager.GetString("SyncIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-Adresse kopiert.
        /// </summary>
        internal static string SyncIpCopied {
            get {
                return ResourceManager.GetString("SyncIpCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP wird ermittelt....
        /// </summary>
        internal static string SyncIpLoad {
            get {
                return ResourceManager.GetString("SyncIpLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Adresse nicht verfügbar. Prüfen Sie Ihre Netzwerk....
        /// </summary>
        internal static string SyncIpNotHere {
            get {
                return ResourceManager.GetString("SyncIpNotHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie auf &quot;Synchronisation starten&quot;.
        /// </summary>
        internal static string SyncLiFour {
            get {
                return ResourceManager.GetString("SyncLiFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stellen Sie sicher, dass beide Geräte im gleichen WLAN-Netzwerk sind (Hotspot aktivieren).
        /// </summary>
        internal static string SyncLiOne {
            get {
                return ResourceManager.GetString("SyncLiOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie die IP-Adresse des anderen Geräts ein.
        /// </summary>
        internal static string SyncLiThree {
            get {
                return ResourceManager.GetString("SyncLiThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starten Sie die Synchronisation auf einem Gerät..
        /// </summary>
        internal static string SyncLiTwo {
            get {
                return ResourceManager.GetString("SyncLiTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netzwerkfehler:.
        /// </summary>
        internal static string SyncNetworkError {
            get {
                return ResourceManager.GetString("SyncNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP des anderen Geräts eingeben....
        /// </summary>
        internal static string SyncPlaceholder {
            get {
                return ResourceManager.GetString("SyncPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisation starten.
        /// </summary>
        internal static string SyncStartSync {
            get {
                return ResourceManager.GetString("SyncStartSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So synchronisieren Sie:.
        /// </summary>
        internal static string SyncSubHeader {
            get {
                return ResourceManager.GetString("SyncSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisation erfolgreich!.
        /// </summary>
        internal static string SyncSuccess {
            get {
                return ResourceManager.GetString("SyncSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wird synchronisiert....
        /// </summary>
        internal static string SyncSyncLoad {
            get {
                return ResourceManager.GetString("SyncSyncLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout: Keine Antwort vom Gerät erhalten.
        /// </summary>
        internal static string SyncTimeoutError {
            get {
                return ResourceManager.GetString("SyncTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung zum Gerät wird hergestellt....
        /// </summary>
        internal static string SyncWillBe {
            get {
                return ResourceManager.GetString("SyncWillBe", resourceCulture);
            }
        }
    }
}
